name: my-webhook-server
hostname: localhost
admission_review_version:
  - v1
  - v1beta1
port: 8080
cert_file: cert/apiserver.crt
key_file: cert/apiserver.key
service_name: my-webhook-pkg
token_path: token/token.txt
kube_api_server_url: https://localhost:6443