---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-service-account
  namespace: default  # 필요에 따라 네임스페이스를 변경하세요

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-service-account
rules:
  - apiGroups: ["*"]   # 모든 API 그룹
    resources: ["*"]    # 모든 리소스
    verbs: ["*"]        # 모든 동작 (get, list, watch, create, update, delete 등)
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["*"]  # get, list, create, update, delete 등

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-service-account-binding
subjects:
  - kind: ServiceAccount
    name: webhook-service-account
    namespace: default  # ServiceAccount가 있는 네임스페이스를 지정
roleRef:
  kind: ClusterRole
  name: webhook-service-account
  apiGroup: rbac.authorization.k8s.io
